### ISSUE TITLE
Padding is not always removed from last block

### ISSUE THREAD

**Issue by jackbentley** [jeskew/php-encrypted-streams#10]
When decrypting a stream. The `eof()` method is used to determine if the block should use `OPENSSL_ZERO_PADDING` or not for the decryption.

https://github.com/jeskew/php-encrypted-streams/blob/master/src/AesDecryptingStream.php#L102

The code essentially says that the logical or should only be applied if it is not the last block in the stream/file. This is if either the `eof()` is false or if the stream size does not equal the current pointer position.

However, `eof` is not reliable to determine if this is the last block or not. It will only return true if you have read past the end of the file. Not if you are at the end of the file. See https://www.php.net/manual/en/function.feof.php#67261

For example, when passing in a `$length` which is exactly the amount that is left to be read in the stream, `eof()` will return false even though all of the data has been read and the stream is at the end. You're required to do an additional `read()` in order to set `eof` correctly.

Subsequently, this means the returned `$plainText` contains the padding characters because they were not removed by `openssl` when the decryption takes place (as it has been disabled by the logical or).

**Comment by jackbentley** [comment]
Caused by https://github.com/guzzle/psr7/issues/129

**Comment by jeskew** [comment]
Thanks for reporting this. I'll take a look at the failing tests, but the approach of moving the buffer from a local to an instance variable seems like the right approach.

**Comment by jackbentley** [comment]
Hey! Thanks for looking at the MR!

I didn't realise the tests were failing. I've fixed the tests as well as adding additional tests which fail without the fix in place. 👍 

If we could look at getting a release out soon that'd be awesome :D

**Comment by jeskew** [comment]
Fixed in [0.3.1](https://packagist.org/packages/jsq/psr7-stream-encryption#0.3.1)
