### ISSUE TITLE
The lib breaks for streams that do not implement getSize()

### ISSUE THREAD

**Issue by dennispopel** [jeskew/php-encrypted-streams#9]
While this all works great with filesystem streams, streams that are not are failing. One such example is https://github.com/violet-php/streaming-json-encoder which cannot tell what the resulting stream size could be (otherwise that would defeat the whole purpose of it).

The issue happens in `AesEncryptingStream::encryptBlock() `on line 114; where the `getSize()` of the underlying stream returns null (and null is a valid return value as per PSR7).

Quick removal of lines 112 through 117 solves the issue, but the tests were made on small data sets.

**Comment by jeskew** [comment]
Fixed in [0.3.1](https://packagist.org/packages/jsq/psr7-stream-encryption#0.3.1)
